### ISSUE TITLE
allow base-orphans-0.9

### ISSUE THREAD

**Issue by amigalemming** [phadej/topograph#13]
`topograph` is required by `cabal-plan` which is in Stackage

**Comment by phadej** [comment]
Will do as part of upgrading to GHC-9.6 effort.

**Comment by phadej** [comment]
Done in #14

**Comment by amigalemming** [comment]
Would you mind to release to Hackage or do a revision?
It blocks Stackage:
https://github.com/commercialhaskell/stackage/issues/6906

**Comment by ysangkok** [comment]
@amigalemming A revision has already been made as far as I can see? See https://hackage.haskell.org/package/topograph-1.0.0.2/revisions/
